export enum NoticeCategory {
  ACADEMIC = 'ACADEMIC',
  ADMINISTRATIVE = 'ADMINISTRATIVE',
  HOSTEL_STUDENT_WELLNESS = 'HOSTEL_STUDENT_WELLNESS',
  CLUB_EVENT = 'CLUB_EVENT',
  INTERNSHIP_OPPORTUNITY = 'INTERNSHIP_OPPORTUNITY',
  OTHERS = 'OTHERS',
}

export enum RecipientType {
  ENTIRE_CAMPUS = 'ENTIRE_CAMPUS',
  UG_ONLY = 'UG_ONLY',
  PG_ONLY = 'PG_ONLY',
  SPECIFIC_DEPARTMENT = 'SPECIFIC_DEPARTMENT',
  SPECIFIC_HOSTEL = 'SPECIFIC_HOSTEL',
  OTHERS = 'OTHERS',
}
